server.port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
    open-in-view: true

springdoc:
  api-docs.path: /docs
  swagger-ui.path: /docs/swagger

googlemaps.apikey: <google-maps-api-key>
